name: release

on:
  push:
    branches:
      # - master
    pull_request:
      # - master

jobs:

  deploy:

    runs-on: ubuntu-latest
    container: clojure:lein
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: deploy config
        run: |
          cd $GITHUB_WORKSPACE
          # setup deployment config
          mv deploy-profiles.clj profiles.clj
      - name: release
        run: lein release
