name: Release

on:
  push:
    branches: [ * ]
  pull_request:
    branches: [ * ]

jobs:

  lein:
    runs-on: ubuntu-latest
    container: clojure:lein
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: debug
        run: |
          cd $GITHUB_WORKSPACE
          pwd
          ls -al
      - name: release
        run: lein deploy clojars
