name: Release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  lein:
    runs-on: ubuntu-latest
    container: clojure:lein
    steps:
      - run: lein release
        name: release
