name: Release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  lein:
    runs-on: ubuntu-latest
    container: clojure:lein
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: release
        run: lein deploy clojars
